# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: express-cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    environment: cicd-demo

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3


    - name: Create .env for server
      working-directory: .
      run: |
        echo "SERVER_ENV=$SERVER_ENV" >> .env
        echo "PORT=$PORT" >> .env
      env:
        SERVER_ENV: ${{ secrets.SERVER_ENV }}
        PORT: ${{ secrets.PORT }}

    - name: Install server dependencies
      working-directory: .
      run: npm install

    - name: Deploy and restart with PM2
      working-directory: .
      run: |
        pm2 restart cicd-demo || pm2 start app.js --name cicd-demo 

